// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgxoZ-N75Eq9hywKyYdIJOVFCGFtZ7Ls',
    appId: '1:920471631331:web:ade65e0e455a1eac80dcd6',
    messagingSenderId: '920471631331',
    projectId: 'trendart-63ec9',
    authDomain: 'trendart-63ec9.firebaseapp.com',
    storageBucket: 'trendart-63ec9.appspot.com',
    measurementId: 'G-RPDWTMG4LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1oSBBgFPPKj7ktrpIfIHAsU5CvgcEcE',
    appId: '1:920471631331:android:eab99c8b281a3aa480dcd6',
    messagingSenderId: '920471631331',
    projectId: 'trendart-63ec9',
    storageBucket: 'trendart-63ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2D79BtwlrFWXKKMqzkvnNckYhYTYkFc',
    appId: '1:920471631331:ios:278dfcf514a4298080dcd6',
    messagingSenderId: '920471631331',
    projectId: 'trendart-63ec9',
    storageBucket: 'trendart-63ec9.appspot.com',
    iosBundleId: 'com.example.trendart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2D79BtwlrFWXKKMqzkvnNckYhYTYkFc',
    appId: '1:920471631331:ios:0a41ab55ecfab6f380dcd6',
    messagingSenderId: '920471631331',
    projectId: 'trendart-63ec9',
    storageBucket: 'trendart-63ec9.appspot.com',
    iosBundleId: 'com.example.trendart.RunnerTests',
  );
}
